### ISSUE TITLE
host:31337/servers - 500 Internal Server Error 

### ISSUE THREAD

**Issue by ewan2395** [pannal/Kitana#1]
- Debian 9.5
- PMS is running behind a NGINX reverse proxy with a custom url using ports 80/443.
- Tested in a virtual Python environment (miniconda3) and Docker container.

**After authenticating through plex the following error is shown:**

`The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/etc/miniconda3/envs/kitana/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/etc/miniconda3/envs/kitana/lib/python3.7/site-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/etc/miniconda3/envs/kitana/lib/python3.7/site-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/etc/miniconda3/envs/kitana/lib/python3.7/site-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "kitana.py", line 412, in servers
    servers = self.discover_pms(server_name=server_name, server_addr=server_addr)
  File "kitana.py", line 335, in discover_pms
    if device["provides"] != "server" or not bool(device["presence"]):
TypeError: string indices must be integers`

**Comment by Escondido** [comment]
Thanks for stepping up with this program in lieu of the recent Plex changes. 

I'm experiencing the exact same issue, but I'm not using a reverse proxy. The software correctly recognizes my servers, however, once I click one I see the same issue as @ewan2395.   The only thing I changed was the directory Kitana was installed in. Portainer shows the program always wants to use /app/data, which doesn't exist on my server. All programs are installed in /opt/appdata/programname here. Should be able to install in that directory with no problems. Am I gonna have to manually change a few of the files or do you recommend a different solution?

**Comment by pannal** [comment]
Do you get the same errors as @ewan2395?

Can you join me on the SZ slack so I can look at your data?

**Comment by pannal** [comment]
@Escondido your issue seems different from @ewan2395, can you get me the error traceback?

And both of you, please [obtain your Plex Token](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/) and visit `https://plex.tv/api/resources?includeHttps=1&includeRelay=1&X-Plex-Token=YOURPLEXTOKEN`, then mask any information you don't want me to have in there and post the output here, please.

Otherwise I can't fix your issues.

**Comment by ewan2395** [comment]
> @Escondido your issue seems different from @ewan2395, can you get me the error traceback?
> 
> And both of you, please [obtain your Plex Token](https://support.plex.tv/articles/204059436-finding-an-authentication-token-x-plex-token/) and visit `https://plex.tv/api/resources?includeHttps=1&includeRelay=1&X-Plex-Token=YOURPLEXTOKEN`, then mask any information you don't want me to have in there and post the output here, please.
> 
> Otherwise I can't fix your issues.

https://hastebin.com/oqorepineb.xml

**Comment by pannal** [comment]
I think I found the issue. Could you try https://github.com/pannal/Kitana/releases/tag/0.1.5b1 ?

**Comment by ewan2395** [comment]
I can now successfully login and select the server but the 'choose_plugin?' page shows a http error 303; Chrome complains of "ERR_TOO_MANY_REDIRECTS".

I've attempted using both http and https from the server list which results in the same error. 

`*.*.**.* - - [01/Nov/2018:11:57:04] "GET /choose_plugin?default_identifier=com.plexapp.agents.subzero HTTP/1.1" 303 102 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
Error when connecting to 'http://plex.********.**:80/', trying other connection to: ********
Server set to: ********, http://plex.********.**:80
Verifying ********: http://plex.********.**:80
Verified ********: http://plex.********.**:80
*.*.**.* - - [01/Nov/2018:11:57:04] "GET / HTTP/1.1" 303 102 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
*.*.**.* - - [01/Nov/2018:11:57:04] "GET / HTTP/1.1" 303 220 "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"`

I am running my reverse proxy through Cloudflare which may contribute to this error. Further investigation is required on this part.

Would it be possible to manually add the server address on the login page. eg: selecting localhost:32400 rather than the external urls?

**Comment by pannal** [comment]
Hmm. Weird, as it seems to be able to connect in the end. Afterwards there's infinite redirects?

I can implement a direct connection field, but I'd like to see where it currently fails.

**Comment by pannal** [comment]
@ewan2395 do you have more than one plugin installed?

**Comment by pannal** [comment]
@ewan2395 can you install the [latest develop version](https://github.com/pannal/Kitana/archive/develop.zip)? I've added more debugging and masked the output of server names and hostnames, so you can simply paste your output here.

It would be nice if we could get to the bottom of this, even though it's working for you now.

**Comment by ewan2395** [comment]
I've installed the latest dev version but it's not giving any more information than before apart from masking the server address.

I have tested with and without Cloudflare and I can rule it out as the culprit; it's nginx for some reason.

nginx error log: https://hastebin.com/anidukexoc.log
my nginx config: https://hastebin.com/sonasuhelo.nginx

**Comment by pannal** [comment]
Also, what happens when you add `-i None` to the kitana command line behind the NGINX?

**Comment by ewan2395** [comment]
I have been connecting to Kitana via IP:PORT; it's Plex which is behind the Nginx reverse proxy. That error is shown when Kitana attempts to connect to the external domain.

I don't particularly want to modify the configuration for the Plex reverse proxy as it's been specifically tweaked for compatibility and performance.

I can connect successfully using local IPs which is perfectly fine for what I'm needing as Kitana will always be hosted on the same box as PMS.

**Comment by pannal** [comment]
Well, using the default buffer size for responses doesn't exactly scream "tweaked for compatibility and performance" to me. 

But doesn't matter much, as this is a configuration issue out of Kitana's scope.

@Escondido did you try the latest develop version to see whether your issues are gone?
