### ISSUE TITLE
Kitana as an Unraid docker?

### ISSUE THREAD

**Issue by cphmichael** [pannal/Kitana#12]
Could you be interested in doing a Kitana docker container for Unraid?

That will probably give you more users because it will be available in the 'Community Applications' and easier to install :-)

Regards
Michael

**Comment by pannal** [comment]
@cphmichael are you up for the task by any chance?

**Comment by cphmichael** [comment]
Unfortunately, I do not know how to make a Docker containe.

**Comment by gilbN** [comment]
@cpmichael there is no such thing as an unraid docker. There are docker containers and unraid docker container templates you use to easily install containers. If you want a container in the CA store you can add an issue here  😉https://github.com/selfhosters/unRAID-CA-templates

**Comment by cphmichael** [comment]
@gilbN Can you help me and request a Kitana unRAID Docker Container?

**Comment by gilbN** [comment]
Use the template here https://github.com/selfhosters/unRAID-CA-templates/issues/new/choose

**Comment by Roxedus** [comment]
Added in selfhosters/unRAID-CA-templates#17, should be in the Unraid Community Applications within a few hours.

**Comment by cphmichael** [comment]
Thank you for your help @Roxedus 

I have tried to search for Kitana in the unRAID Comunity Applications, but I can not find it?

Regards
Michael 

![kitana](https://user-images.githubusercontent.com/45288008/66110454-1aa84a00-e5c7-11e9-9bb1-fd85df2c119b.PNG)

**Comment by Roxedus** [comment]
It had some initial errors, it made its way into CA 13 minutes ago. Squidly271/AppFeed@ee9b505

**Comment by cphmichael** [comment]
I have installed Kitana from the Community Applications, but the WebUI do not work.

In the installation it says: "
To set the baseurl for this application, open advanced view, and add -p /kitana -P to the "Post Arguments"

The Post Arguments says: -B 0.0.0.0:31337 -p /kitana -P
so I think it is already set.

Does the container works for you?

**Comment by Roxedus** [comment]
Yes. when a baseurl is set you need to add /kitana (if that was the path you set) you need to add that to the url. Kitana doesnt redirect, just answers with a 404

**Comment by cphmichael** [comment]
Ahh, that works - Thank you very much :-)

**Comment by pannal** [comment]
Is this solved?

**Comment by cphmichael** [comment]
Yes, @Roxedus fixed it :-)

**Comment by pannal** [comment]
Great, closing, thank you
