### ISSUE TITLE
What now?

### ISSUE THREAD

**Issue by nedludd** [pannal/Kitana#13]
For us noobies you might want to add some documentation of what to do once you have Kitana installed.

Once I started up Kitana all I saw was:

`No viable plugins found; please choose a different server`

I finally figured out that I have to place the plugin bundles in the `Plug-Ins` directory of my Plex server.  But that was not obvious. (Yes I know that is part of the old Plex installation routine, but I thought Kitana would handle that for me.)

Thanks

**Comment by nedludd** [comment]
By the way, I installed Sub-Zero this way, and all I see in the Kitana interface is `I'm not enabled`.  

I can configure Sub-Zero through the Plex interface.

**Comment by pannal** [comment]
Kitana is just a frontend for existing Plex plugins, which is stated in the README.

As for "I'm not enabled" - this is the wrong place to ask, but you have to enable the agent at least for one media type. See SZ Wiki.

**Comment by pannal** [comment]
@nedludd ?

**Comment by frakman1** [comment]
@nedludd To expand on pannal's vague answer here:

> As for "I'm not enabled" - this is the wrong place to ask, but you have to enable the agent at least for one media type. See SZ Wiki.

The Wiki page he mentions is [here](https://github.com/pannal/Sub-Zero.bundle/wiki/FAQ#q5-sub-zero-reports-please-enable-me-currently-i-do-nothing)

For me, I had to go to Plex's Agents Settings and enable SubZero there. See screenshot below:
![image](https://user-images.githubusercontent.com/5826484/88412221-39224080-cda7-11ea-8d3f-8c52268a56ce.png)

I also had to go to my library in the Plex WebUI  and select "Refresh All Metadata" before I saw the subtitle in the movie.
For reference, the `.srt` file is also downloaded into the same folder of the movie.

The error message (`Please enable me for some of your libraries in your server settings; currently I do nothing`) is really unhelpful and doesnt really tell you where to go, expecially after hearing that the Plugin can't be configured via Plex's WebUI (There is nothing under the `Plugins` page). It's confusing that you have to go into Plex's WebUI to enable it!

I hope that helps someone.
