### ISSUE TITLE
Unable to launch kitana Ubuntu

### ISSUE THREAD

**Issue by dualznz** [pannal/Kitana#14]
`root@roman-server:/opt/Kitana# python kitana.py

  File "kitana.py", line 685
    versioned_asset.replace("/", os.sep))}, )
                                          ^
SyntaxError: invalid syntax`

OS: Ubuntu 16.04-3 LTS Server
Installed pip requirements but cannot launch server

**Comment by pannal** [comment]
Please post the output of `python -V`

**Comment by pannal** [comment]
@dualznz ?
