### ISSUE TITLE
No CSS in Kitana via Docker?

### ISSUE THREAD

**Issue by jonathanlaniado** [pannal/Kitana#15]
See below, not really sure what to make of it. Kitana is functional otherwise.

![image](https://user-images.githubusercontent.com/8929491/65129368-fb4ad380-d9af-11e9-88d8-8ef779c8f0b7.png)

**Comment by pannal** [comment]
How do you host it and access it? Also please post docker command line, chrome network window screenshot and app log.

**Comment by tzw9373** [comment]
This is the issue I'm seeing currently as well, running on Windows 10 and Ubuntu 18.04.

**Comment by jonathanlaniado** [comment]
@pannal, I'm using Ubuntu 18.04, docker-compose to build it, and Traefik to host it. The Kitana piece of my docker-compose file looks like this:

```
kitana:
  container_name: kitana
  image: 'pannal/kitana:latest'
  restart: always
  volumes:
    - ${USERDIR}/Documents/docker/kitana/kitana_data:/app/data
  ports:
    - "31337:31337"
  networks:
    - traefik_proxy
  labels:
    - "traefik.enable=true"
    - "traefik.backend=kitana"
    - "traefik.frontend.rule=Host:kitana.${DOMAINNAME}"
    - "traefik.port=31337"
    - "traefik.docker.network=traefik_proxy"

**Comment by jonathanlaniado** [comment]
@pannal, I'm not sure how I missed this the first time, but right after posting the above, I noticed that Chrome was blocking some of the content. **Load Unsafe Scripts** temporarily fixes the issue, but perhaps there is a long-term fix?

![image](https://user-images.githubusercontent.com/8929491/65193744-16115c80-da31-11e9-92f2-21f6616ee796.png)

**Comment by pannal** [comment]
The backend needs to know that HTTPS was used. Not sure how to do that with traefik.

**Comment by pannal** [comment]
@jonathanlaniado look here, I forgot that I added those settings: https://github.com/pannal/Kitana/issues/7#issuecomment-533649010

**Comment by jonathanlaniado** [comment]
@pannal, that's perfect! For those using docker-compose and a reverse proxy, add `command: -P` to your docker-compose.yml file to fix this issue.
