### ISSUE TITLE
Raspberry Pi 

### ISSUE THREAD

**Issue by mouzzampk2014** [pannal/Kitana#16]
Hi, can I use this docker with raspberry pi? Thank you

**Comment by pannal** [comment]
Why shouldn't you be able to? Are there any restrictions?

**Comment by mouzzampk2014** [comment]
Basically I am not sure which tag I need to use for raspberry pi
    ```image: pannal/kitana:latest

**Comment by pannal** [comment]
No, please try that tag and report any issues.

**Comment by pablokbs** [comment]
I can confirm the "latest" tag only points to the amd64 version, are you guys using automatic builds from DockerHub? Because it currently [doesn't support buildx](https://github.com/docker/hub-feedback/issues/1779) ... so the only way to have the armhf being created is to move the build step to another solution (circle CI is a good alternative)

**Comment by pannal** [comment]
Anything I can do here?

**Comment by pablokbs** [comment]
Yes, answer this:

> are you guys using automatic builds from DockerHub? 

If not, how are you building the images?

**Comment by pannal** [comment]
Manually. `docker build --rm --pull -t kitana .`.

**Comment by pablokbs** [comment]
Alright, do you need help with the commands or you've got it?

**Comment by pannal** [comment]
Well, I could use help with CircleCI, but currently I'm simply cross-compiling using `docker buildx build --rm --pull --platform linux/amd64,linux/arm64,linux/arm/v7 -t pannal/kitana:latest .`. Is that enough to cover most of the platforms?

Thank you :)

**Comment by pannal** [comment]
Kitana should now available as arm64 and arm7 @mouzzampk2014

**Comment by pablokbs** [comment]
I can confirm that it runs fine on a raspberry pi now :+1:

```
kbs@raspberrypi2:~ $ docker run pannal/kitana:0.1.9
Unable to find image 'pannal/kitana:0.1.9' locally
0.1.9: Pulling from pannal/kitana
ffb3a1edd2f5: Pull complete
68e451b65286: Pull complete
b396d1056bcb: Pull complete
21ee8c0d5fd4: Pull complete
ab438d17d846: Pull complete
7caa630204a5: Pull complete
d95e86aff1ad: Pull complete
61330b8cc651: Pull complete
58903357202a: Pull complete
d36182158791: Pull complete
Digest: sha256:3ab80132b1c237e118c725689aafc67e77e5f3a1b2cab55459c1c2e4d10a59c1
Status: Downloaded newer image for pannal/kitana:0.1.9
[25/Oct/2019:14:12:58] ENGINE Bus STARTING
[25/Oct/2019:14:12:58] ENGINE Starting SassCompilerPlugin
[25/Oct/2019:14:12:58] ENGINE Started monitor thread 'UpdateCheck'.
[25/Oct/2019:14:12:58] ENGINE Serving on http://0.0.0.0:31337
[25/Oct/2019:14:12:58] ENGINE Bus STARTED
[25/Oct/2019:14:12:58]  Starting Sass Compile
[25/Oct/2019:14:12:58]  SassCompilerPlugin: Compiling /app/static/sass to /app/static/css
[25/Oct/2019:14:13:02] ENGINE Listening for SIGUSR1.
[25/Oct/2019:14:13:02] ENGINE Listening for SIGHUP.
[25/Oct/2019:14:13:02] ENGINE Listening for SIGTERM.
```

**Comment by pablokbs** [comment]
BTW [this is a guide](https://circleci.com/blog/using-circleci-workflows-to-replicate-docker-hub-automated-builds/) to automatically build your images with CircleCI on each new version.

CircleCI is free for a single project and only 1 concurrent job, which is more than enough for your case

**Comment by mouzzampk2014** [comment]
Thank you so much. Working fine :) 
Thanks again
