### ISSUE TITLE
'Get my logs' does not works.

### ISSUE THREAD

**Issue by cphmichael** [pannal/Kitana#19]
My Plex server is installed in a data-center at the University of Copenhagen.

My Plex server IP-address is: 10.60.154.11

The University has different external addresses in the range 130.225. and 130.226.

I remote connect to the server with VPN.

Kitana are running in a Docker container on my Plex server.

When I start the Kitana docker container I see errors:
* Error when connecting to 'https://192-***

When I in Kitana try to 'Get my logs', Kitana open a page 

https://130.225.98.253:32400/video/subzero/logs?X-Plex-Token=RSrG_fDgvDdxMQVLytmm

I get the error:

This site can’t be reached130.225.98.253 unexpectedly closed the connection.

It seems like the 'redirecting' confusing Kitana.

I have attached the Kitana docker log.

Maybe you can see what the problem is :-)

[Kitana.txt](https://github.com/pannal/Kitana/files/3771571/Kitana.txt)

**Comment by pannal** [comment]
pannal/Sub-Zero.bundle#696

@cphmichael but you can access SZ using Kitana properly, right?

**Comment by pannal** [comment]
With 0.2.0 this should be fixed. You'll have to re-select your server before this works.
