### ISSUE TITLE
CURL support?

### ISSUE THREAD

**Issue by mzglinski** [pannal/Kitana#20]
I'm wondering whether there is a proper way to trigger some actions using curl (in my case inside a cronjob).

When plugins were available in standard plex app I was using a cronjob for subtitles refresh (because I spin down my HDD when it's not in use and standard SZ Scheduler without an option to set exact time wasn't cutting it for me). This was my command to do it:
```
http://192.168.11.10:32400/video/subzero/missing/refresh
```
I didn't need `X-Plex-Token` because I configured plex to trust connections from same machine. 

I was hoping to achieve something similar with Kitana, and eventually, I did by injecting `kitana_docker_session_id` cookie into my curl request but I have my doubts about the long term viability of such solution (mainly because I suspect that it will expire after some time).

Am I missing something? Maybe you have some recommendations for a better solution? If not can you share for how long that cookie will work before being logged out?

**Comment by pannal** [comment]
You can still do what you did before. The web handlers still exist for plugins (that's what Kitana uses).

**Comment by mzglinski** [comment]
Whoa, you are right, thanks. My problem was with the switch from HTTP to HTTPS.  Thanks.
