### ISSUE TITLE
An option to Install the latest SZ DEV from Kitana Advanced?

### ISSUE THREAD

**Issue by cphmichael** [pannal/Kitana#21]
To make it easier for people to help development SZ and install the latest SZ DEV, I would like to ask if it is possible to implement an option for that in Kitana > Advanced menu?

Maybe also an option to rollback, if there is a problem with the latest SZ DEV.

**Comment by ukdtom** [comment]
Kitana doesn't have file access to the PMS, and as such, would be hard to put files on ;)

**Comment by pannal** [comment]
Well, this might be possible using an API endpoint of SZ. I'll think about it :)

**Comment by ukdtom** [comment]
Then it's not install, but upgrade, or?

**Comment by pannal** [comment]
Well no, as it should be using the same user/group as the PMS does, it's able to write to the Plug-Ins folder. I'm not sure whether Kitana can trigger restarts via the PMS API, though.

**Comment by ukdtom** [comment]
If you mean restart to pick up new one, simply restart the system bundle
`HTTP.Request('http://127.0.0.1:32400/:/plugins/com.plexapp.system/restart', immediate=True)`

And then only for an upgrade ;)
(Since SZ API is only avail if already installed)
