### ISSUE TITLE
Start kitana from systemd

### ISSUE THREAD

**Issue by trunet** [pannal/Kitana#24]
systemd is available almost everywhere. as an example, see below:

/etc/systemd/system/kitana.service:
```
[Unit]
Description=Plex Kitana Web
After=network.target

[Service]
Type=simple
WorkingDirectory=/opt/Kitana
Environment=PYTHONPATH=/opt/Kitana
ExecStart=/opt/Kitana/.venv/bin/python kitana.py
Restart=on-failure

[Install]
WantedBy=multi-user.target
```

**Comment by bigdant** [comment]
When i use the above, i get this error message:-

Dec 17 17:20:43 raspberrypi python3[6918]:     output.append(listener(*args, **kwargs))
Dec 17 17:20:43 raspberrypi python3[6918]:   File "/opt/Kitana/plugins/SassCompilerPlug
Dec 17 17:20:43 raspberrypi python3[6918]:     shutil.rmtree(str(css_directory))
Dec 17 17:20:43 raspberrypi python3[6918]:   File "/usr/lib/python3.5/shutil.py", line 
Dec 17 17:20:43 raspberrypi python3[6918]:     _rmtree_safe_fd(fd, path, onerror)
Dec 17 17:20:43 raspberrypi python3[6918]:   File "/usr/lib/python3.5/shutil.py", line 
Dec 17 17:20:43 raspberrypi python3[6918]:     onerror(os.unlink, fullname, sys.exc_inf
Dec 17 17:20:43 raspberrypi python3[6918]:   File "/usr/lib/python3.5/shutil.py", line 
Dec 17 17:20:43 raspberrypi python3[6918]:     os.unlink(name, dir_fd=topfd)
Dec 17 17:20:43 raspberrypi python3[6918]: PermissionError: [Errno 13] Permission denie
lines 1-17/17 (END)

**Comment by pannal** [comment]
Well, this clearly is a permission issue. You might want to have a look at who's running Kitana and which user the systemd script is running as.

**Comment by agneevX** [comment]
I've settled on this. 
```
[Unit]
Description=Kitana
Requires=plexmediaserver.service
After=plexmediaserver.service

[Service]
Type=simple
ExecStart=/usr/bin/python3.7 /opt/Kitana/kitana.py
Restart=on-failure
User=<user_name>
Group=<group_name>

[Install]
WantedBy=multi-user.target
```
