### ISSUE TITLE
KITANA DOCKER - MIXED CONTENT ERROR

### ISSUE THREAD

**Issue by Cyb3rGh05t** [pannal/Kitana#26]
hey,

i need some help regarding KITANA DOCKER.

i am running Kitana over nginx proxy server with a specific subdomain, but when i load the page i get an error in google_chrome.

UNSAFE SCRIPTS

![image](https://user-images.githubusercontent.com/5200101/71555942-f3c8ab00-2a31-11ea-9a56-31588eb8c05a.png)

does somebody know how i can fix this?

My Nginx Config looks like this:

`#Upstream to kitana
upstream kitana {
    server ip_to_server:65535;
    keepalive 32;
}

server {
    listen 443 http2 ssl;

    server_name kitana.mystreamnet.club;
        
        include snippets/ssl-params.conf;
    
        send_timeout 100m;

    ssl_certificate /etc/letsencrypt/live/kitana.mystreamnet.club/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kitana.mystreamnet.club/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/kitana.mystreamnet.club/fullchain.pem;

    gzip on;
    gzip_vary on;
    gzip_min_length 1000;
    gzip_proxied any;
    gzip_types text/plain text/css text/xml application/xml text/javascript application/x-javascript image/svg+xml;
    gzip_disable "MSIE [1-6]\.";

    client_max_body_size 100M;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_redirect off;
    proxy_buffering off;

        location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/var/run/php/php7.0-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location / {
              proxy_pass http://kitana;
    }

        
}

server {
        listen 80;
        listen [::]:80;
        server_name kitana.mystreamnet.club;
        return 301 https://$server_name$request_uri;
}`

Thanks in advance..

**Comment by pannal** [comment]
Try adding `-P` to the command line of kitana and see whether that helps. This tells Kitana to assume it runs behind a reverse proxy, which it does in your case.

**Comment by pannal** [comment]
You might also need `-PB https://kitana.mystreamnet.club` (maybe with a `/` at the end), but try with `-P` only first.

**Comment by Cyb3rGh05t** [comment]
thanks for the reply... :)

I'msorry but i not really sure what you mean with your suggestion? 
I am new to proxies and docker stuff :( i am using installing everything over plexgude project.

**Comment by pannal** [comment]
Well you need to change the way the Kitana container starts: https://github.com/pannal/Kitana#mount-on-kitana-and-behind-a-reverse-proxy-example-nginx

It needs -P at least to work behind a reverse proxy as a command line parameter.

**Comment by pannal** [comment]
I've never used portainer, judging from the wiki, it only supports overwriting the command used, not the option to add parameters.

You can try setting the command to `python kitana.py -P` on the kitana container.

**Comment by Cyb3rGh05t** [comment]
ok thank you, i will see if i could figure it out.

thanks for taking time

**Comment by Cyb3rGh05t** [comment]
allright got it :)

![image](https://user-images.githubusercontent.com/5200101/71583493-fbaa4d00-2b0e-11ea-898b-ae225e1a92d7.png)

i really appreciate that you took some time to help me out :)

Thanks a lot and happy new year :)

**Comment by pannal** [comment]
Ah can you detail how you entered the necessary data into the interface? I'll add that to the README then.

**Comment by pannal** [comment]
@Cyb3rGh05t?

**Comment by Cyb3rGh05t** [comment]
Sorry i was away for a few days :(

First i opened kitana docker in portainer to get the container details.
Then i clicked on DUPLICATE/EDIT option.

![image](https://user-images.githubusercontent.com/5200101/71668023-ac128e00-2d67-11ea-9eef-3c0e7a8de87b.png)

In ADVANCED SETTINGS i added the command '-B' '0.0.0.0:31337' '-P'

![image](https://user-images.githubusercontent.com/5200101/71668143-0d3a6180-2d68-11ea-895e-c800749d485e.png)

then i redeployed the container

![image](https://user-images.githubusercontent.com/5200101/71668208-41ae1d80-2d68-11ea-86e8-f385cc4e1f18.png)

**Comment by saitoh183** [comment]
@Cyb3rGh05t 

Thank you for sharing

@pannal 

You should add this to the Wiki as many people use portainer as there docker frontend

**Comment by saitoh183** [comment]
im trying to get it to work with reverse proxy nginx with /katana...all i get is a blank screen when i try it from from the docker ip 127.20.0.21:31337/katana (or without katana)
and https//:domain.com/katana gives page cant be found
I copied from the sample conf
```
#Kitana
    location ^~ /kitana/pms_asset {
      expires 1M;
      access_log off;
      add_header Cache-Control "public";
      proxy_redirect off;
      proxy_pass http://kitana:31337;
    }
	location /kitana/ {
      proxy_pass http://kitana:31337;
    }
```

**Comment by pannal** [comment]
No idea to be honest. Does NGINX like spaces after the location comparator?

**Comment by saitoh183** [comment]
> No idea to be honest. Does NGINX like spaces after the location comparator?

It shouldnt matter cuz if it did , it wouldnt start up properly

**Comment by pannal** [comment]
Well, if it works without NGINX in front of it, it's not Kitana's fault.

My NGINX reverse proxy config looks like this:
```
location ^~ /kitana/pms_asset {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
        proxy_pass http://127.0.0.1:31337;
        include proxy.conf;
        add_header Transport 'dynamic';
    }

    location ^~ /kitana/static/  {
        root /bulk/;

        # versioned static rewrite
        rewrite "^(\/kitana\/static\/(css|js|img)\/)(\w+)\.\w{7}\.(\w{2,4})$" $1$3.$4 last;
    }

    location /kitana/ {
        proxy_pass http://127.0.0.1:31337;
        include proxy.conf;
        add_header Transport 'dynamic';
    }
```

**Comment by saitoh183** [comment]
i will try your config...i know its not kitana, its nginx but i couldnt find the way to add it properly

**Comment by saitoh183** [comment]
It works :)

thanks @pannal

**Comment by TristBella** [comment]
Maybe you guys can help me. I have kitana installed and working without NGINX. I also use Portainer and have it set as above. When i add to NGINX, even using pannal config, it will 404. https://domain.com/kitana will work till it goes to https://domain.com/token. So I added "token" into the config. Now it craps out at https://domain.com/choose_plugin?XXXXXXXXXXXX. Am I going to need to add every "location" that kitana is looking for? Just for the heck of it, I have also added a volume to the kitana data from the letsencrypt container.

`location ^~ /kitana/pms_asset {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
        proxy_pass http://127.0.0.1:31337;
        include /config/nginx/proxy.conf;
        add_header Transport 'dynamic';
    }

    location ^~ /kitana/static/  {
        root /bulk/;

        # versioned static rewrite
        rewrite "^(\/kitana\/static\/(css|js|img)\/)(\w+)\.\w{7}\.(\w{2,4})$" $1$3.$4 last;
    }

    location /kitana/ {
        proxy_pass http://127.0.0.1:31337;
        include /config/nginx/proxy.conf;
        add_header Transport 'dynamic';
    }

	location /token {
		proxy_pass http://127.0.0.1:31337/token;
        include /config/nginx/proxy.conf;
        add_header Transport 'dynamic';
    }`

**Comment by pannal** [comment]
You didn't set the prefix and/or behind proxy mode. Please see Readme.

**Comment by lgkahn** [comment]
trying to run on windows  for plex all requirements ment and installed i get this error
E:\kitana>python3.9 kitana.py
Traceback (most recent call last):
  File "E:\kitana\kitana.py", line 28, in <module>
    from plugins.SassCompilerPlugin import SassCompilerPlugin
ModuleNotFoundError: No module named 'plugins'

E:\kitana>
thanks
