### ISSUE TITLE
Docker not updating

### ISSUE THREAD

**Issue by saitoh183** [pannal/Kitana#29]
I tried latest and image 0.3.1-3 and it still sticks on 0.2.0

![image](https://user-images.githubusercontent.com/1534197/74892726-6c742580-5358-11ea-98ea-30e242fb09c0.png)

![image](https://user-images.githubusercontent.com/1534197/74892754-7dbd3200-5358-11ea-8072-cb6292cc4e8a.png)

**Comment by pannal** [comment]
Did you try removing and re-adding it? I don't use your management tool/interface.

When doing it manually, there's always a removal step involved: `docker stop kitana && docker rm kitana && docker pull pannal/kitana:latest`

**Comment by saitoh183** [comment]
basically thats what i did in portainer. It works with all my other containers. but i will try it via cli directly

**Comment by saitoh183** [comment]
Fixed, it was because i had forgot i pointed the volume towards /app and not /app/data because i was testing something and forgot to change it back.
