### ISSUE TITLE
Not able to access externally

### ISSUE THREAD

**Issue by CelticWebSolutions** [pannal/Kitana#30]
I've installed via the docker container and I can't seem to access it on the external network.  I've port forwarded the 31337 port and also edited the sample config files with the domain name I'd be accessing it from.  I still can only access it on the local network.  

Is this normal or am I doing something wrong? Thanks in advance for the help!

**Comment by CelticWebSolutions** [comment]
Anybody have any suggetsions here?

**Comment by pannal** [comment]
What's your command line?
