### ISSUE TITLE
Installation information wrong?

### ISSUE THREAD

**Issue by Nemesis77swe** [pannal/Kitana#31]
As a newbie; (to Linux), regarding the installation of requirements.txt, you wrote on the web to use `pip install -r requirements.txt` should it not be `pip3 install -r requirements.txt` since it requires python 3.5+ ?

**Comment by Cimplex** [comment]
Just as a side note, some people don't have 2.7 install and as such alias "pip3" as just "pip". That said, it did confuse me too.

**Comment by pannal** [comment]
Well, since 2.7 is officially unsupported since 01/01/20, I think this can stand. Also the Readme clearly states which python version to use.

**Comment by Nemesis77swe** [comment]
Now I don't follow, isn't pip3 for python3, and pip is for earlier versions (2.7), and since the 2.7 isn't supported anymore, you should use pip3, or am I missing something?

**Comment by pannal** [comment]
You're absolutely right. I expect `pip` to be replaced with the `pip3` version by default, though, as 2.7 is gone.

**Comment by Nemesis77swe** [comment]
That may take a long time, a few (for example Tautulli) are still only compatible with 2.7, and as a newbie, you don't always know the difference..

**Comment by pannal** [comment]
Good point, fixing README.
