### ISSUE TITLE
No viable plugins found

### ISSUE THREAD

**Issue by Keatnisher** [pannal/Kitana#36]
Hi,

I receive the message "No viable plugins found; please choose a different server".

I am running kitana standalone on Ubuntu and I have placed plug-ins at:

/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Plug-ins/

but Kitana can't recognize them. Does the location of kitana-master matter? What am I missing?

**Comment by ukdtom** [comment]
Is the plugin loaded?

Aka: In the WebClient, under agents, does it show there?

And if not, then check rights to the plugin directory

**Comment by Keatnisher** [comment]
No it doesn't look like the plugins are loaded. What should the rights to the plugin directory be?

Originally it was:

drwxr-xr-x 6 plex plex 4096 Mar 23 02:35 Plug-ins

and for the plugins:

drwxrwxr-x 3 usr grp 4096 Mar 23 01:27 Sub-Zero.bundle

I tried changing these around and restarting the server but haven't found a combination that works.

**Comment by ukdtom** [comment]
As the originally, and recursively

**Comment by Keatnisher** [comment]
Ah, that was it - I wasn't chmod/chown recursively. Thanks!
