### ISSUE TITLE
added to plexguide

### ISSUE THREAD

**Issue by Admin9705** [pannal/Kitana#4]
just a note to you! great work!

https://plexguide.com

<img width="573" alt="xnip2018-11-29_20-52-14" src="https://user-images.githubusercontent.com/24727006/49263469-ab971d80-f418-11e8-8c49-7e76d9628624.png">

**Comment by pannal** [comment]
Do you use Kitana in docker mode? If so, do you use the recommended command line with the /app/data mount and does that work by default?
