### ISSUE TITLE
Standalone installer for Windows?

### ISSUE THREAD

**Issue by viking2** [pannal/Kitana#43]
On reddit I saw your comment " I'd suggest running the standalone release though, not the docker one". Where can I find the Windows Installer?
Thank you,

**Comment by viking2** [comment]
Note that I am not even able to install Docker since I am running Windows 7.

**Comment by pannal** [comment]
There's no Windows installer. Install a supported Python 3 version (>3.5), download Kitana, and follow the installation instructions.
