### ISSUE TITLE
Sub-Zero+Kitana or Bazarr?

### ISSUE THREAD

**Issue by viking2** [pannal/Kitana#44]
I upgraded to latest Plex on WIN7 and lost the UI for Sub-Zero.  I use Sonarr and CouchPotato and occasionally download TV shows/Movies manually. I also plan to migrate to Radarr.
Would you recommend using Sub-Zero+Kitana or Bazarr?
(Sorry to post here but the reddit threads were closed)

**Comment by pannal** [comment]
Both have their benefits. Please try them and decide for yourself. I still use SZ and Kitana personally.

**Comment by viking2** [comment]
I am not able to install docker since I am using Windows 7. Is there a windows installer for Kitana?
