### ISSUE TITLE
Use Kitana without a Plex account?

### ISSUE THREAD

**Issue by SamGurdus1** [pannal/Kitana#50]
I've been using my server without a Plex account for privacy reasons. I'd like to install some plugins, but since the channels tab was removed, they don't work.

I found Kitana, but it seems to require the use of a Plex account tied to the server. It doesn't seem likely to me, but I figure it's worth asking: 

Can Kitana be used without a Plex account? (or if not, can I use it with an account that's not tied to the server?)

**Comment by pannal** [comment]
It might be possible to achieve what you're seeking.

Kitana would have to run on the same network as your PMS and would need a special option. I'll investigate.
