### ISSUE TITLE
Can't get it started on windows

### ISSUE THREAD

**Issue by JelledFro** [pannal/Kitana#52]
I followed the instruction for a manual windows install, but the listed ip show nothing. What is the output supposed to be? Is kitana started even? I don't see any error message. 

![image](https://user-images.githubusercontent.com/36453510/107153636-e7ba5700-696e-11eb-9cd1-b46ec5266bd6.png)
.

**Comment by pannal** [comment]
0.0.0.0 means it listenes on any interface.
Try http://127.0.0.1:31337 or http://your-pcs-lan-ip:31337.

Otherwise you can specify the IP to listen on in the command line.

**Comment by JelledFro** [comment]
I see. Thanks! working now :)
