### ISSUE TITLE
TV Section Missing

### ISSUE THREAD

**Issue by Escondido** [pannal/Kitana#58]
I'm not 100% sure if this is a Plex/Subzero or Kitana issue.  The TV section is missing when I visit Recently-added items, Browse all items, etc. and I cannot search for any shows. I also keep seeing a timeout error when visiting other sections. I'm using the latest version of Plex and Kitana.  Any ideas how to fix it?

**Comment by pannal** [comment]
Are you on Windows? https://github.com/pannal/Sub-Zero.bundle/issues/764

**Comment by Escondido** [comment]
No, I'm using Linux. Pretty much been using Kitana since you first released it and haven't experienced this issue before. I'm using the standalone plugins.  Is there any difference between them vs your bundle?

**Comment by Escondido** [comment]
I figured out the solution.  I changed the Agent for TV shows to Plex TV series and that caused the issue. Changing it back to TheTVDB and restarting the plugin fixed the issue.

**Comment by pannal** [comment]
Yes, the new agents don't call Python at all, which is why you need to stick to the old ones (mostly called "Legacy")
