### ISSUE TITLE
open to all users?

### ISSUE THREAD

**Issue by amanalar** [pannal/Kitana#6]
not sure if it's intended or if there's a setting I missed. I enabled this using windows docker. One of my friends said he could go into plugins and see my youtube. Meaning my subscriptions and history. Same for subzero, he can go in and change settings. 

Is that intended? I was kind of hoping people would use the plugins and enable YouTubeTV.bundle for themselves;

Also, is there a way to hideplugins? I rather not have the outside world be able to change SZ or WebTools plugins.

thanks,

**Comment by pannal** [comment]
Kitana is a plugin proxy for Plex. It mirrors exactly what it receives from the PMS - for the user that's currently requesting a plugin list.

If your settings allow your friends to access plugins (I wasn't aware this was possible), they can do that.

> One of my friends said he could go into plugins and see my youtube.

I'm not sure how the YT plugin works. If it has a centralized user configured and only works that way, that's how it'll behave. Again, nothing Kitana can change.

I can add a restriction to only allow certain plugins for non-owner users for example, but that's about it.

**Comment by pannal** [comment]
> In your description you wrote "Kitana exposes your Plex plugin interfaces "to the outside world".

Ah yeah I see how that can be understood that way. I'll rephrase that. 

After the new year I'll try to get a new build out with the whitelist/blacklist feature.

How do your users access the plugins remotely? Are they using locally enabled/family accounts and not the sharing (for which plugins doesn't seem to work)?

**Comment by amanalar** [comment]
Thanks for that, all my users are under sharing not home users

**Comment by pannal** [comment]
Then I might be misunderstanding you there. They actually can access your plugins remotely?

**Comment by amanalar** [comment]
Yes, tested on second account as a sharing user. I have access to plugins

**Comment by pannal** [comment]
Ok, weird. I can't access the plugins of the servers shared with me at all. It won't even let me connect to the servers properly. 

How would you like the whitelist/blacklist to work? It won't really keep someone from using their own kitana instance to access your plugins then. It will only keep them from using your plugins using your kitana instance.

**Comment by amanalar** [comment]
Oh hmm, I know this isn't what you intended, would it be possible to block some plugins from accessing the outside world

**Comment by ukdtom** [comment]
Late to the party here ;)

But in WebTools, I only allow access if user is the server owner

https://github.com/ukdtom/WebTools.bundle/blob/master/Contents/Code/plextvhelper.py#L63
