### ISSUE TITLE
not working on latest windows 10

### ISSUE THREAD

**Issue by lgkahn** [pannal/Kitana#70]
installed will not run on windows 10.. get the follownig error

E:\kitana>python3.9 kitana.py
Traceback (most recent call last):
  File "E:\kitana\kitana.py", line 28, in <module>
    from plugins.SassCompilerPlugin import SassCompilerPlugin
ModuleNotFoundError: No module named 'plugins'

troed to install package

E:\kitana>pip3.9 install plugins
ERROR: Could not find a version that satisfies the requirement plugins
ERROR: No matching distribution found for plugins

**Comment by pannal** [comment]
`pip install requirements_win32.txt`
