### ISSUE TITLE
The connection to the site cannot be established.

### ISSUE THREAD

**Issue by bulletproof2k** [pannal/Kitana#78]
The connection to the site cannot be established.
Page at http://0.0.0.0:31337 / may be temporarily unavailable or moved to a new address.
![2022-10-29_01-43-02](https://user-images.githubusercontent.com/1818579/198746848-b691406a-faa7-448e-963d-1492b899f0a7.png)

**Comment by pannal** [comment]
https://en.wikipedia.org/wiki/0.0.0.0

**Comment by bulletproof2k** [comment]
Thanks for the answer, but I didn't understand what needs to be done.
