### ISSUE TITLE
bad syntax in kitana.py on qnap aarch64

### ISSUE THREAD

**Issue by lukjod** [pannal/Kitana#9]
I have such problem after install on qnap aarch64 device

File "kitana.py", line 678
versioned_asset.replace("/", os.sep))}, )
^
SyntaxError: invalid syntax

any help? what logs needed to debug?

Python3 3.6.3.1.1 from Qnap

[~] # pip -V
pip 19.2.2 from /opt/lib/python3.7/site-packages/pip (python 3.7)

**Comment by pannal** [comment]
I can't really reproduce this. Can you send me that exact kitana.py?

Also your pip seems to be from python 3.7, but you said 3.6.3.1.1.

**Comment by lukjod** [comment]
ahh, sry qnap package which installs python is version 3.6.31
[https://www.qnap.com/pl-pl/app_releasenotes/list.php?app_choose=Python3](url)

**Comment by lukjod** [comment]
i did try to install that again and it stops on libsass
`[~] # pip install -r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt
Collecting cherrypy==18.0.1 (from -r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/15/5f/eac3cedec7c7befba60cf93926e2a813a760a826aefa0780d9196d4cc52d/CherryPy-18.0.1-py2.py3-none-any.whl
Collecting requests==2.20.0 (from -r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/f1/ca/10332a30cb25b627192b4ea272c351bce3ca1091e541245cccbace6051d8/requests-2.20.0-py2.py3-none-any.whl
Collecting xmltodict==0.11.0 (from -r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/42/a9/7e99652c6bc619d19d58cdd8c47560730eb5825d43a7e25db2e1d776ceb7/xmltodict-0.11.0-py2.py3-none-any.whl
Collecting libsass==0.15.0 (from -r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/00/e4/28f7fc87da16f2d0a982a01856b10bff2bc52d87b850fdf86196ebade4f9/libsass-0.15.0.tar.gz
Collecting future-fstrings==0.4.4 (from -r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/90/32/6bb42916d91cf9e548f90b95f15c5d951c691c29b97d4a7ec9385d6c1700/future_fstrings-0.4.4-py2.py3-none-any.whl
Collecting jinja2 (from -r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/1d/e7/fd8b501e7a6dfe492a433deb7b9d833d39ca74916fa8bc63dd1a4947a671/Jinja2-2.10.1-py2.py3-none-any.whl
Collecting pyGitHub==1.43.2 (from -r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/91/9e/50af4bb0ab316fedc13ae87347a718c19698ba8a19e64a692dc30c5fc9db/PyGithub-1.43.2.tar.gz
Collecting furl==2.0.0 (from -r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/bd/b6/302ecc007de38274509d6397300afd2e274aba7f1c3c0a165b5f1e1a836a/furl-2.0.0-py2.py3-none-any.whl
Requirement already satisfied: more-itertools in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from cherrypy==18.0.1->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1)) (7.2.0)
Requirement already satisfied: zc.lockfile in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from cherrypy==18.0.1->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1)) (2.0)
Requirement already satisfied: cheroot>=6.2.4 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from cherrypy==18.0.1->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1)) (6.5.6)
Requirement already satisfied: portend>=2.1.1 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from cherrypy==18.0.1->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1)) (2.5)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from requests==2.20.0->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from requests==2.20.0->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 2)) (2019.6.16)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from requests==2.20.0->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 2)) (1.24.3)
Requirement already satisfied: idna<2.8,>=2.5 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from requests==2.20.0->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 2)) (2.7)
Requirement already satisfied: six in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from libsass==0.15.0->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 4)) (1.12.0)
Requirement already satisfied: MarkupSafe>=0.23 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from jinja2->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 6)) (1.1.1)
Requirement already satisfied: pyjwt in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from pyGitHub==1.43.2->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 7)) (1.7.1)
Requirement already satisfied: Deprecated in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from pyGitHub==1.43.2->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 7)) (1.2.6)
Requirement already satisfied: orderedmultidict>=1.0 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from furl==2.0.0->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 8)) (1.0.1)
Requirement already satisfied: setuptools in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from zc.lockfile->cherrypy==18.0.1->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1)) (40.6.2)
Requirement already satisfied: backports.functools-lru-cache in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from cheroot>=6.2.4->cherrypy==18.0.1->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1)) (1.5)
Requirement already satisfied: tempora>=1.8 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from portend>=2.1.1->cherrypy==18.0.1->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1)) (1.14.1)
Requirement already satisfied: wrapt<2,>=1.10 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from Deprecated->pyGitHub==1.43.2->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 7)) (1.11.2)
Requirement already satisfied: pytz in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from tempora>=1.8->portend>=2.1.1->cherrypy==18.0.1->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1)) (2019.2)
Requirement already satisfied: jaraco.functools>=1.20 in /share/CACHEDEV1_DATA/.qpkg/Entware/lib/python3.7/site-packages (from tempora>=1.8->portend>=2.1.1->cherrypy==18.0.1->-r /share/CACHEDEV1_DATA/.qpkg/Entware/Kitana/requirements.txt (line 1)) (2.0)
Installing collected packages: cherrypy, requests, xmltodict, libsass, future-fstrings, jinja2, pyGitHub, furl
  Running setup.py install for libsass ... -
`

**Comment by pannal** [comment]
Might this be the same as #10 10?

**Comment by pannal** [comment]
Can you try https://github.com/Raph521/Kitana/blob/master/Dockerfile.armhf?

**Comment by lukjod** [comment]
After try to install using container station on qnap using
`pannal/kitana
Name: kitana-1
commmand: docker run --name kitana -v kitana_data:/app/data -d -p 0.0.0.0:31337:31337 pannal/kitana:latest -B 0.0.0.0:31337
entry point: python kitana.py`

when try to start it i get
`standard_init_linux.go:185: exec user process caused "exec format error"
standard_init_linux.go:185: exec user process caused "exec format error"
standard_init_linux.go:185: exec user process caused "exec format error"`

**Comment by pannal** [comment]
Hmm you shouldn't try installing sass and libsass, they might conflict. `pip3 install -r requirements.txt` should be enough.

Did you try that specific docker file? https://github.com/pannal/Kitana/issues/9#issuecomment-527703913

**Comment by lukjod** [comment]
Yes, after install of docker i had to manually install all dependencies in requirement.txt there is a problem to install Libya's as it hangs during install
